# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Johnsons Baby
url: https://johnsonsbaby.github.io/
feed: /feed.xml
author_info: <a href="https://johnsonsbaby.github.io/">Johnsons Baby</a>

myblog:
  gavatar: images/avatar.png
  gpname: jsbd
  github: https://github.com/johnsonsbaby
  email: mailto:johnsonsbaby@126.com
  coverimgs: []
  postbgimg: []

categories: [linux, python, reading, world]

theme: jekyll-theme-cayman